apiVersion: core.choreo.dev/v1beta1
kind: Endpoint
metadata:
  name: spring-boot-test
spec:
  host: spring-boot-test.choreo.dev
  paths:
    - path: /*
      backend:
        service:
          name: spring-boot-test
          port: 8080