apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
metadata:
  name: spring-boot-test
spec:
  type: api
  source:
    git:
      repositoryUrl: https://github.com/nalakadissnayake/spring-boot-test.git
      branch: master
      context: /
    build:
      runtime: java-17
      buildCommand: mvn clean package
      startCommand: mvn spring-boot:run
  ports:
    - containerPort: 8080
      protocol: HTTP
  routes:
    - path: /hello
      method: GET
      target:
        containerPort: 8080